name: MyFirstPlugin
version: '1.0-SNAPSHOT'
main: me.tharle.myFirstPlugin.MyFirstPlugin
api-version: '1.21'
authors: [ Tharle ]
description: Tutorial Spigot puglin MC
website: tharle.ca
commands:
  die:
    description: You kill other players or yourself
    usage: /<command>
  god:
    description: Turn on or off the invulnerability
    usage: /<command>
    aliases:
      - deus
      - dieux
  feed:
    description: Feed the player
    usage: /<command>
    permission: permissions.feed
    permission-message: You dont have permission to run the command /feed.
  hungry:
    description: let the player a little more hungry
    permission: permissions.hungry
    permission-message: You dont have permission to run the command /hungry.
    usage: /<command>
  setspawn:
    description: set your spawn
    usage: /<command>
  spawn:
    description: teleport you to the spawn (you need to set the spawn place with /setspawn before)
    usage: /<command>
  kill:
    description: kill some player by name
    usage: /<command> <arg>
  gift:
    description: give to you a item or two.
    usage: /<command>
  menu:
    description: Open to you a custom inventory to find some nice itens
    usage: /<command>
permissions:
  permissions.feed:
    description: Allows someone to run the /feed command.
    default: op
    children:
      permissions.hungry: true